# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7624f394bd62f30e158b3cbe3d99ea9263076ed284aff0e1ad3cc48cbf9dcf0c8a7ace84802961f231478211f054a110d9bc0d45c0a45161fed4ea3ea433ee29

test:
  secret_key_base: f7e60151a56889287d270a7d47cae77c643d5bbfa052a0986b52049216779289ff9f2712f76c341a693686f85cb90d9c11cd33cf7a6b05d1cb6f8eca77e5683b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
